# API testing for our Library API's
# Protocals: http://
# URL: localhost
# port: :8000
# path: api/v1/users or books or admin-users

@rootApi = http://localhost:8000/api/v1/users

# ===== admin user
### create new admin usere
POST {{rootApi}}/admin-user
Content-Type: application/json

{
    "fname": "Gaurav",
    "lname": "Shreenet",
    "email": "a@a.com",
    "phone": "0451352524",
    "password": "12345"
}

### Login usere
POST {{rootApi}}/login
Content-Type: application/json

{
   
    "email": "b@b.com",
    "password": "123456"
}

# ===== student user
### get students profile
GET {{rootApi}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJAYi5jb20iLCJpYXQiOjE3MDE2NTk3MjksImV4cCI6MTcwMTY2MDYyOX0.DL3JdVvN8FUbO7twrbCC8040ZyRO0uwMCyIzfyNxp0o


###create new students account
POST {{rootApi}}