# API testing for our Library API's
# Protocals: http://
# URL: localhost
# port: :8000
# path: api/v1/users or books or admin-users

@rootApi = http://localhost:8000/api/v1/users

# ===== admin user
### create new admin usere
POST {{rootApi}}/admin-user
Content-Type: application/json

{
    "fname": "Gaurav",
    "lname": "Shreenet",
    "email": "a@a.com",
    "phone": "0451352524",
    "password": "12345"
}

# ===== student user
### get students profile
GET {{rootApi}}


###create new students account
POST {{rootApi}}